### ISSUE TITLE
kuzzle_wrapper_add_listener only iterate once on messages

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/sdk-wrappers#37]
The `kuzzle_wrapper_add_listener` method only iterate once and stops watching for messages.

:warning: at the moment, there is no way to stop the channel to be listened at. As an effect, the go thread can't be stopped leading to thread leaks.

All subscribe methods use the same paradigm, a discussion should take place to align our vision about Go / CGo subscriptions.

**Comment by ballinette** [comment]
will be deprecader by sdk refactoring
